name: sushibox
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  uni_links: ^0.5.1
  location: ^7.0.0
  flutter_secure_storage: ^9.2.2
  flutter_gen: ^5.6.0
  intl: any
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  dio: ^5.5.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.1.3
  vibration: ^1.9.0
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.15.1
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_lints: ^4.0.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
