name: resturant_delivery_boy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.5
  get_it: ^7.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  google_maps_flutter: ^2.2.5
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.1.11
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.0
  path_provider: ^2.0.14
  vibration: ^1.7.6
  shimmer: ^3.0.0
  flutter_widget_from_html_core: ^0.15.1
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_lints: ^4.0.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  phone_number: ^2.0.0
  country_code_picker: ^3.0.0
  dotted_border: ^2.0.0+3




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
