name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  dio: ^5.1.2
  http: any
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.8
  google_maps_flutter: ^2.7.0
  flutter_google_places: any
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  shimmer_animation: ^2.2.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  url_strategy: ^0.2.0
  carousel_slider: ^4.2.1
  universal_html: ^2.2.4
  image: ^4.2.0
  flutter_widget_from_html_core: any
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  flutter_typeahead: ^5.2.0
  fwfh_selectable_text: ^0.8.3
  circular_countdown_timer: ^0.2.3
  timezone: ^0.9.4
  marquee: ^2.2.3
  flutter_inappwebview: ^6.0.0
  google_api_headers: any
  audioplayers: ^6.0.0
  flutter_facebook_auth: any
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  share_plus: ^9.0.0
  expandable_bottom_sheet: ^1.1.1
  scroll_to_index: ^3.0.1
  google_maps_webservice: any
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  just_the_tooltip: ^0.0.12
  sign_in_with_apple: ^6.1.1
  mobile_scanner: ^5.1.1
  app_links: ^6.1.3
  go_router: ^14.2.0
  firebase_auth: ^5.1.1







dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/
    - assets/json/
    - assets/payment/
    - assets/
    - web/assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400